version: '3.2'

services:
  poxa:
    build:
      context: ./
      dockerfile: DockerfilePoxa
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - POXA_APP_KEY=app_key
      - POXA_SECRET=secret
      - POXA_APP_ID=app_id
